---
  - name: get hugepage size
    command: awk '/Hugepagesize/ {print $2 }' /proc/meminfo
    register: hugepage_result

  - name: assign hugepage size
    set_fact:
      hugepage_size: "{{ hugepage_result.stdout }}"

  - name: compute hugepages
    set_fact:
      role_num_hugepages: "{{ [((ansible_memtotal_mb - reserved_mem_mb) / (ansible_processor_count * huge_page_size_mb))|int if ((ansible_memtotal_mb - reserved_mem_mb) / (ansible_processor_count * huge_page_size_mb))|int, max_num_hugepages]|min }}"
