# Copyright (c) 2017, Intel Corporation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

---
  - fail:
      msg: "Not enought memory to auto set hugepages (reserved_mem_mb: {{ reserved_mem_mb }})."
    when: ansible_memtotal_mb - reserved_mem_mb <= 0 and num_hugepages == "auto"

  - name: Detect EFI
    stat: path="/sys/firmware/efi"
    register: efi

  - name: check if hugepages are set by this role
    command: "grep -o '{{ hugepage_param_regex }}' /etc/default/grub"
    register: is_mine_huge
    ignore_errors: True

  - name: check if hugepages are set by someone else
    command: "grep -o 'default_hugepagesz=' /etc/default/grub"
    register: is_huge
    ignore_errors: True

  - fail:
      msg: "Hugepages already set by someone else"
    when: is_mine_huge.stdout == "" and is_huge.stdout != ""

  - set_fact:
      role_num_hugepages: "{{ num_hugepages }}"

  - include: auto.yml
    when: huge_page_size_mb == 2 and num_hugepages == "auto"

  - name: use 16 for auto num_hugepages and 1G size
    set_fact:
      role_num_hugepages: 16
    when: role_num_hugepages == "auto"

  - name: set hugepages in grub
    lineinfile:
      dest: /etc/default/grub
      regexp: '{{ hugepage_param_regex }}'
      line: '{{ hugepage_param }}'
      state: present

  - name: Update grub
    command: "{{ update_grub[ansible_os_family] }}"
